connect 'jdbc:derby:BUSINESS_NAMES_DB;create=true';

DROP TABLE BN_REGISTRATIONS;

DROP TABLE BN_STATUS;

DROP TABLE BN_NAMES;

DROP TABLE BN_STATES;

DROP TABLE BN_STATUS_OPTIONS;


CREATE TABLE BN_NAMES(ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY, REGISTER_NAME VARCHAR(14), BN_NAME VARCHAR(200));

CREATE TABLE BN_STATUS_OPTIONS(BN_STATUS_ID BOOLEAN NOT NULL PRIMARY KEY, BN_STATUS VARCHAR(12));

CREATE TABLE BN_STATUS(ID INT NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) REFERENCES BN_NAMES(ID), BN_STATUS_ID BOOLEAN REFERENCES BN_STATUS_OPTIONS(BN_STATUS_ID), BN_REG_DT DATE, BN_CANCEL_DT DATE, BN_RENEW_DT DATE);

CREATE TABLE BN_STATES(BN_STATE_OF_REG SMALLINT NOT NULL PRIMARY KEY, STATE VARCHAR(3));

CREATE TABLE BN_REGISTRATIONS(ID INT NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) REFERENCES BN_NAMES(ID), BN_STATE_NUM  VARCHAR(10), BN_STATE_OF_REG SMALLINT REFERENCES BN_STATES(BN_STATE_OF_REG), BN_ABN VARCHAR(20));


CALL SYSCS_UTIL.SYSCS_IMPORT_DATA (NULL, 'BN_NAMES', 'REGISTER_NAME, BN_NAME', NULL, 'BUS_NAMES.csv', NULL, NULL, NULL, 0);

CALL SYSCS_UTIL.SYSCS_IMPORT_DATA (NULL, 'BN_STATUS_OPTIONS', 'BN_STATUS_ID, BN_STATUS', NULL, 'BUS_STATUS_OPTIONS.csv', NULL, NULL, NULL, 0);

CALL SYSCS_UTIL.SYSCS_IMPORT_DATA (NULL, 'BN_STATUS', 'BN_STATUS_ID, BN_REG_DT, BN_CANCEL_DT, BN_RENEW_DT', NULL, 'BUS_STATUS.csv', NULL, NULL, NULL, 0);

CALL SYSCS_UTIL.SYSCS_IMPORT_DATA (NULL, 'BN_STATES', 'BN_STATE_OF_REG, STATE', NULL, 'BUS_STATES.csv', NULL, NULL, NULL, 0);

CALL SYSCS_UTIL.SYSCS_IMPORT_DATA (NULL, 'BN_REGISTRATIONS', 'BN_STATE_NUM, BN_STATE_OF_REG, BN_ABN', NULL, 'BUS_REGS.csv', NULL, NULL, NULL, 0);
